# Generated by Django 4.2 on 2025-06-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='total_certificate_hours',
            field=models.FloatField(default=0.0, help_text='Общее количество часов, полученных в сертификатах'),
        ),
    ]
