# Generated by Django 4.2 on 2025-06-30 14:57

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_scanner_total_certificate_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLeader',
        ),
        migrations.CreateModel(
            name='TeamLeaderUser',
            fields=[
            ],
            options={
                'verbose_name': 'Тим лидер (пользователь)',
                'verbose_name_plural': 'Тим лидеры (пользователи)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scanner', models.ForeignKey(blank=True, help_text='Связанный аккаунт сканера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamleader_profile', to='core.scanner')),
            ],
        ),
    ]
