# Generated by Django 4.2 on 2025-06-30 15:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_delete_teamleader_teamleaderuser_teamleader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleader',
            name='scanner',
        ),
        migrations.DeleteModel(
            name='TeamLeaderUser',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
            ],
            options={
                'verbose_name': 'Тим лидер',
                'verbose_name_plural': 'Тим лидеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
