# Generated by Django 4.2 on 2025-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_teamleader_teamleaderuser_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='hours_awarded_backup',
            field=models.FloatField(default=0.0),
        ),
    ]
