# Generated by Django 4.2 on 2025-07-01 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_teamleader_teamleaderuser_teamleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.models.validate_english_only]),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.models.validate_english_only]),
        ),
    ]
