# Generated by Django 4.2 on 2025-12-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_eventparticipant_hours_awarded_backup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterModelOptions(
            name='teamleaderuser',
            options={'verbose_name': 'Ответственный', 'verbose_name_plural': 'Ответственные'},
        ),
    ]
