# Generated by Django 4.2 on 2025-07-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_alter_scanner_first_name_alter_scanner_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purge_date', models.DateField(help_text='Дата, в которую будет происходить ежегодное удаление мероприятий', verbose_name='Дата ежегодного обновления')),
                ('notification_days_before', models.IntegerField(default=7, help_text='За сколько дней до удаления отправлять уведомления', verbose_name='Дней до уведомления')),
                ('active', models.BooleanField(default=True, help_text='Включить/выключить автоматическое удаление', verbose_name='Активно')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Настройка обновления базы',
                'verbose_name_plural': 'Настройки обновления базы',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_test', models.BooleanField(default=False, verbose_name='Тестовое уведомление')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-sent_at'],
            },
        ),
    ]
