# Generated by Django 4.2 on 2025-07-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_purgesettings_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=10, verbose_name='Тип уведомления'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID получателя'),
        ),
        migrations.AddField(
            model_name='scanner',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Telegram', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Telegram', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email получателя'),
        ),
    ]
