# Generated by Django 4.2 on 2025-12-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_eventparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='volunteer',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='scanner',
        ),
        migrations.RemoveField(
            model_name='teamleaderprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
        migrations.DeleteModel(
            name='TeamLeaderProfile',
        ),
    ]
