# Generated by Django 4.2 on 2025-07-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificationlog_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purgesettings',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
